### ISSUE TITLE
[tm_json.h] GCC warns about multiline string comment

### ISSUE THREAD

**Issue by fluffrabbit** [to-miz/tm#1]
When compiling with gcc -Wall -Wpedantic in C++11 mode I get this warning. I would suggest a block comment instead.

```
tm_json.h:305:5: warning: multi-line comment [-Wcomment]
     // "property": "this is a multiline \
     ^
```

**Comment by to-miz** [comment]
Thanks, fixed in bf92ceb153a7a355c2be969ab86b2c673f0ff5e1.
